name=UUtzinger_logger
version=2.1.1
author=Urs Utzinger
maintainer=Urs Utzinger
sentence=Library for Arduino logging over Print outputs
paragraph=Provides printf-style logging over Serial or another Print output with configurable log levels, LOG, LOGln, LOGI, LOGW, LOGE, LOGD, custom %b binary formatting, optional simple vsnprintf formatting, and optional USE_AUDIO_LOGGING macro conflict avoidance.
url=https://github.com/uutzinger/logger
category=Other
architectures=*
includes=logger.h
